import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    // Navigation
    menu: 'Menu',
    ourStory: 'Notre histoire',
    locations: 'Locaux',
    contact: 'Contact',
    dashboard: 'Dashboard',
    cart: 'Panier',
    logout: 'Déconnexion',
    order: 'Commander',
    noAccount: 'Pas encore de compte ?',
    
    // Home
    eyebrow: 'Poperinge, Belgique',
    title1: 'Votre café,',
    title2: 'votre rythme.',
    subtitle: 'Commandez à l\'avance, récupérez sans attendre. Vriends Poperinge, c\'est le café de quartier qui respecte votre temps.',
    orderNow: 'Commander maintenant',
    viewMenu: 'Voir le menu',
    discountBadge: '−10%',
    forLocals: 'Pour les locaux',
    openToday: 'Ouvert aujourd\'hui',
    quote: '"Un endroit où tout le monde se connaît."',
    hoursWeek: 'Lun — Ven',
    hoursWeekend: 'Sam — Dim',
    hoursWeekTime: '7h30 — 17h',
    hoursWeekendTime: '8h — 15h',
    feature1Title: 'Commande à l\'avance',
    feature1Text: 'Préparez votre commande la veille et récupérez-la sans attendre le lendemain.',
    feature2Title: 'Réductions locales',
    feature2Text: 'Vous habitez Poperinge ? Bénéficiez automatiquement de -10% sur toutes vos commandes.',
    feature3Title: 'Retrait rapide',
    feature3Text: 'Zéro attente. Votre commande est prête à l\'heure choisie, vous passez juste la récupérer.',
    ourSelection: 'Notre sélection',
    menuOfTheMoment: 'Le menu du moment',
    viewAllMenu: 'Tout le menu →',
    youAreFromPoperinge: 'Vous êtes de Poperinge ?',
    localAdvantages: 'Rejoignez notre programme local et profitez d\'avantages exclusifs réservés aux habitants de Poperinge.',
    autoDiscount: 'Réduction automatique',
    priorityAccess: 'Accès prioritaire',
    community: 'Communauté Vriends',
    
    // Contact
    contactUs: 'Contactez-nous',
    name: 'Nom',
    email: 'Email',
    phone: 'Telephone',
    message: 'Message',
    required: '*',
    consent: 'J\'accepte d\'être recontacté(e) par Vriends Poperinge (RGPD)',
    send: 'Envoyer le message',
    sending: 'Envoi...',
    scanQR: 'Scanner pour accéder au formulaire',
    downloadQR: '↓ Télécharger le QR Code',
    address: 'Rue de la Station, Poperinge',
    hours: 'Lun-Ven 7h30-17h · Sam-Dim 8h-15h',
    emailContact: 'info@vriendspoperinge.be',
    messageSent: 'Message envoyé !',
    messageSuccess: 'Merci, votre message a bien été envoyé. Nous vous répondrons dans les plus brefs délais.',
    sendAnother: 'Envoyer un autre message',
    
    // Register
    register: 'Inscription',
    fullName: 'Nom complet',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    addressField: 'Adresse',
    city: 'Ville',
    postalCode: 'Code postal',
    localResident: 'Je suis résident(e) de Poperinge',
    alreadyAccount: 'Déjà un compte ?',
    login: 'Se connecter',
    registerButton: 'S\'inscrire',
    registering: 'Inscription...',
    accountCreated: 'Compte créé ! Vous pouvez vous connecter.',
    passwordMinLength: 'Le mot de passe doit contenir au moins 8 caractères',
    passwordsDontMatch: 'Les mots de passe ne correspondent pas',
    specialOffer: 'Offre spéciale pour Poperinge',
    discountMessage: 'Trop bien ! Tu bénéficies de -10% de réduction réservée aux habitants de Poperinge.',
    localOffer: 'Offre locale Vriends',
    localOfferText: 'Tu habites à Poperinge ? Profite de -10% de réduction sur ta commande.',
    dontShowAgain: 'Ne plus afficher',
    
    // Login
    loginTitle: 'Connexion',
    createAccount: 'Créer un compte',
    loginButton: 'Se connecter',
    logging: 'Connexion...',
    passwordLabel: 'Mot de passe',
    loginError: 'Erreur de connexion',
    
    // Menu
    ourMenu: 'Notre Menu',
    menuSubtitle: 'Découvrez notre sélection de produits frais préparés chaque jour.',
    addToCart: 'Ajouter',
    unavailable: 'Indisponible',
    addedToCart: 'Ajouté au panier ✓',
    
    // Cart
    yourCart: 'Votre panier',
    emptyCart: 'Votre panier est vide',
    viewMenu: 'Voir le menu',
    subtotal: 'Sous-total',
    discount: 'Remise',
    total: 'Total',
    pickupTime: 'Heure de retrait',
    placeOrder: 'Passer la commande',
    placingOrder: 'Commande en cours...',
    remove: 'Supprimer',
    cartEmpty: 'Votre panier est vide',
    orderSuccess: 'Commande passée avec succès !',
    summary: 'Récapitulatif',
    orderNumber: 'Commande',
    
    // Profile
    profile: 'Mon profil',
    identity: 'Identité',
    advantages: 'Avantages',
    orders: 'Mes commandes',
    localBadge: 'Résident local',
    noDiscount: 'Aucune remise active',
    discountActive: 'Remise active',
    noOrders: 'Aucune commande',
    orderStatus: 'Statut',
    pickupTimeLabel: 'Heure de retrait',
    pending: 'En attente',
    ready: 'Prêt',
    completed: 'Terminée',
    cancelled: 'Annulée',
    disconnect: 'Se déconnecter',
    
    // Dashboard
    orders: 'Commandes',
    products: 'Produits',
    contactsLeads: 'Contacts & Leads',
    users: 'Utilisateurs',
    new: 'Nouveau',
    treated: 'Traité',
    read: 'Lire',
    markTreated: 'Marquer traité',
    markUntreated: 'Marquer non traité',
    delete: 'Supprimer',
    exportCSV: 'Exporter CSV',
    qrCodeConfig: 'Configuration QR Code',
    qrCodeDestinationUrl: 'URL de destination du QR Code',
    edit: 'Modifier',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    saving: 'Sauvegarde...',
    qrCodeUrlUpdated: 'URL du QR Code mise à jour avec succès !',
    qrCodeUrlInfo: 'Cette URL est la destination vers laquelle le QR code redirigera. Le QR code lui-même pointe vers une page de redirection fixe (`/qr-redirect`) qui utilise cette URL.',
    qrScans: 'Scans QR Code',
    totalScans: 'Total',
    today: 'Aujourd\'hui',
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois',
    pickupTimeLabel: 'Heure de retrait',
    orderTotal: 'Total',
    changeStatus: 'Changer le statut',
    available: 'Disponible',
    unavailable: 'Indisponible',
    toggle: 'Basculer',
    admin: 'Admin',
    client: 'Client',
    nonLocal: 'Non local',
    reduction: 'Réduction',
    noContactsToExport: 'Aucun contact à exporter',
    noUsersToExport: 'Aucun utilisateur à exporter',
    deleteContactConfirm: 'Supprimer ce contact ?',
    
    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    allFieldsRequired: 'Tous les champs obligatoires doivent être remplis',
    consentRequired: 'Le consentement est requis',
  },
  nl: {
    // Navigation
    menu: 'Menu',
    ourStory: 'Ons verhaal',
    locations: 'Locaties',
    contact: 'Contact',
    dashboard: 'Dashboard',
    cart: 'Winkelwagen',
    logout: 'Afmelden',
    order: 'Bestellen',
    noAccount: 'Nog geen account?',
    
    // Home
    eyebrow: 'Poperinge, België',
    title1: 'Jouw koffie,',
    title2: 'jouw ritme.',
    subtitle: 'Bestel op voorhand, haal op zonder te wachten. Vriends Poperinge is de buurtkoffie die je tijd respecteert.',
    orderNow: 'Nu bestellen',
    viewMenu: 'Menu bekijken',
    discountBadge: '−10%',
    forLocals: 'Voor locals',
    openToday: 'Vandaag open',
    quote: '"Een plek waar iedereen elkaar kent."',
    hoursWeek: 'Ma — Vr',
    hoursWeekend: 'Za — Zo',
    hoursWeekTime: '7u30 — 17u',
    hoursWeekendTime: '8u — 15u',
    feature1Title: 'Vooraf bestellen',
    feature1Text: 'Bereid uw bestelling de avond tevoren voor en haal deze de volgende dag op zonder te wachten.',
    feature2Title: 'Lokale kortingen',
    feature2Text: 'Woont u in Poperinge? Geniet automatisch van -10% op al uw bestellingen.',
    feature3Title: 'Snelle ophaling',
    feature3Text: 'Geen wachttijd. Uw bestelling is klaar op het gekozen tijdstip, u hoeft alleen maar langs te komen.',
    ourSelection: 'Onze selectie',
    menuOfTheMoment: 'Menu van het moment',
    viewAllMenu: 'Volledige menu →',
    youAreFromPoperinge: 'Bent u van Poperinge?',
    localAdvantages: 'Sluit u aan bij ons lokale programma en geniet van exclusieve voordelen voor inwoners van Poperinge.',
    autoDiscount: 'Automatische korting',
    priorityAccess: 'Prioritaire toegang',
    community: 'Vriends gemeenschap',
    
    // Contact
    contactUs: 'Neem contact op',
    name: 'Naam',
    email: 'E-mail',
    phone: 'Telefoon',
    message: 'Bericht',
    required: '*',
    consent: 'Ik accepteer dat Vriends Poperinge contact met mij opneemt (AVG)',
    send: 'Bericht verzenden',
    sending: 'Verzenden...',
    scanQR: 'Scan om toegang te krijgen tot het formulier',
    downloadQR: '↓ QR Code downloaden',
    address: 'Stationstraat, Poperinge',
    hours: 'Ma-Vr 7u30-17u · Za-Zo 8u-15u',
    emailContact: 'info@vriendspoperinge.be',
    messageSent: 'Bericht verzonden!',
    messageSuccess: 'Bedankt, uw bericht is verzonden. We nemen zo snel mogelijk contact met u op.',
    sendAnother: 'Nog een bericht verzenden',
    
    // Register
    register: 'Registratie',
    fullName: 'Volledige naam',
    password: 'Wachtwoord',
    confirmPassword: 'Wachtwoord bevestigen',
    addressField: 'Adres',
    city: 'Stad',
    postalCode: 'Postcode',
    localResident: 'Ik ben inwoner van Poperinge',
    alreadyAccount: 'Al een account?',
    login: 'Inloggen',
    registerButton: 'Registreren',
    registering: 'Registreren...',
    accountCreated: 'Account aangemaakt! U kunt nu inloggen.',
    passwordMinLength: 'Het wachtwoord moet minimaal 8 tekens bevatten',
    passwordsDontMatch: 'De wachtwoorden komen niet overeen',
    specialOffer: 'Speciale aanbieding voor Poperinge',
    discountMessage: 'Geweldig! Je krijgt -10% korting exclusief voor inwoners van Poperinge.',
    localOffer: 'Lokaal aanbod Vriends',
    localOfferText: 'Woon je in Poperinge? Geniet van -10% korting op je bestelling.',
    dontShowAgain: 'Niet meer tonen',
    
    // Login
    loginTitle: 'Inloggen',
    createAccount: 'Account aanmaken',
    loginButton: 'Inloggen',
    logging: 'Inloggen...',
    passwordLabel: 'Wachtwoord',
    loginError: 'Inlogfout',
    
    // Menu
    ourMenu: 'Ons Menu',
    menuSubtitle: 'Ontdek onze selectie van dagelijks vers bereide producten.',
    addToCart: 'Toevoegen',
    unavailable: 'Niet beschikbaar',
    addedToCart: 'Toegevoegd aan winkelwagen ✓',
    
    // Cart
    yourCart: 'Uw winkelwagen',
    emptyCart: 'Uw winkelwagen is leeg',
    viewMenu: 'Menu bekijken',
    subtotal: 'Subtotaal',
    discount: 'Korting',
    total: 'Totaal',
    pickupTime: 'Ophaaltijd',
    placeOrder: 'Bestelling plaatsen',
    placingOrder: 'Bestelling wordt geplaatst...',
    remove: 'Verwijderen',
    cartEmpty: 'Uw winkelwagen is leeg',
    orderSuccess: 'Bestelling succesvol geplaatst!',
    summary: 'Samenvatting',
    orderNumber: 'Bestelling',
    
    // Profile
    profile: 'Mijn profiel',
    identity: 'Identiteit',
    advantages: 'Voordelen',
    orders: 'Mijn bestellingen',
    localBadge: 'Lokale inwoner',
    noDiscount: 'Geen actieve korting',
    discountActive: 'Actieve korting',
    noOrders: 'Geen bestellingen',
    orderStatus: 'Status',
    pickupTimeLabel: 'Ophaaltijd',
    pending: 'In afwachting',
    ready: 'Klaar',
    completed: 'Voltooid',
    cancelled: 'Geannuleerd',
    disconnect: 'Afmelden',
    
    // Dashboard
    orders: 'Bestellingen',
    products: 'Producten',
    contactsLeads: 'Contacten & Leads',
    users: 'Gebruikers',
    new: 'Nieuw',
    treated: 'Behandeld',
    read: 'Lezen',
    markTreated: 'Als behandeld markeren',
    markUntreated: 'Als niet behandeld markeren',
    delete: 'Verwijderen',
    exportCSV: 'CSV exporteren',
    qrCodeConfig: 'QR Code configuratie',
    qrCodeDestinationUrl: 'Bestemmings-URL van QR Code',
    edit: 'Bewerken',
    save: 'Opslaan',
    cancel: 'Annuleren',
    saving: 'Opslaan...',
    qrCodeUrlUpdated: 'QR Code URL succesvol bijgewerkt!',
    qrCodeUrlInfo: 'Deze URL is de bestemming waarnaar de QR code zal doorverwijzen. De QR code zelf wijst naar een vaste doorverwijspagina (`/qr-redirect`) die deze URL gebruikt.',
    qrScans: 'QR Code scans',
    totalScans: 'Totaal',
    today: 'Vandaag',
    thisWeek: 'Deze week',
    thisMonth: 'Deze maand',
    pickupTimeLabel: 'Ophaaltijd',
    orderTotal: 'Totaal',
    changeStatus: 'Status wijzigen',
    available: 'Beschikbaar',
    unavailable: 'Niet beschikbaar',
    toggle: 'Schakelen',
    admin: 'Admin',
    client: 'Klant',
    nonLocal: 'Niet lokaal',
    reduction: 'Korting',
    noContactsToExport: 'Geen contacten om te exporteren',
    noUsersToExport: 'Geen gebruikers om te exporteren',
    deleteContactConfirm: 'Dit contact verwijderen?',
    
    // Common
    loading: 'Laden...',
    error: 'Fout',
    success: 'Succes',
    allFieldsRequired: 'Alle verplichte velden moeten worden ingevuld',
    consentRequired: 'Toestemming is vereist',
  },
  en: {
    // Navigation
    menu: 'Menu',
    ourStory: 'Our Story',
    locations: 'Locations',
    contact: 'Contact',
    dashboard: 'Dashboard',
    cart: 'Cart',
    logout: 'Logout',
    order: 'Order',
    noAccount: 'Don\'t have an account yet?',
    
    // Home
    eyebrow: 'Poperinge, Belgium',
    title1: 'Your coffee,',
    title2: 'your rhythm.',
    subtitle: 'Order in advance, pick up without waiting. Vriends Poperinge is the neighborhood coffee shop that respects your time.',
    orderNow: 'Order now',
    viewMenu: 'View menu',
    discountBadge: '−10%',
    forLocals: 'For locals',
    openToday: 'Open today',
    quote: '"A place where everyone knows each other."',
    hoursWeek: 'Mon — Fri',
    hoursWeekend: 'Sat — Sun',
    hoursWeekTime: '7:30 AM — 5 PM',
    hoursWeekendTime: '8 AM — 3 PM',
    feature1Title: 'Order in advance',
    feature1Text: 'Prepare your order the day before and pick it up without waiting the next day.',
    feature2Title: 'Local discounts',
    feature2Text: 'Do you live in Poperinge? Automatically get -10% off all your orders.',
    feature3Title: 'Quick pickup',
    feature3Text: 'Zero wait time. Your order is ready at the chosen time, you just come to pick it up.',
    ourSelection: 'Our selection',
    menuOfTheMoment: 'Menu of the moment',
    viewAllMenu: 'Full menu →',
    youAreFromPoperinge: 'Are you from Poperinge?',
    localAdvantages: 'Join our local program and enjoy exclusive benefits reserved for Poperinge residents.',
    autoDiscount: 'Automatic discount',
    priorityAccess: 'Priority access',
    community: 'Vriends community',
    
    // Contact
    contactUs: 'Contact us',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    required: '*',
    consent: 'I accept to be contacted by Vriends Poperinge (GDPR)',
    send: 'Send message',
    sending: 'Sending...',
    scanQR: 'Scan to access the form',
    downloadQR: '↓ Download QR Code',
    address: 'Station Street, Poperinge',
    hours: 'Mon-Fri 7:30 AM-5 PM · Sat-Sun 8 AM-3 PM',
    emailContact: 'info@vriendspoperinge.be',
    messageSent: 'Message sent!',
    messageSuccess: 'Thank you, your message has been sent. We will get back to you as soon as possible.',
    sendAnother: 'Send another message',
    
    // Register
    register: 'Register',
    fullName: 'Full name',
    password: 'Password',
    confirmPassword: 'Confirm password',
    addressField: 'Address',
    city: 'City',
    postalCode: 'Postal code',
    localResident: 'I am a resident of Poperinge',
    alreadyAccount: 'Already have an account?',
    login: 'Log in',
    registerButton: 'Register',
    registering: 'Registering...',
    accountCreated: 'Account created! You can now log in.',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordsDontMatch: 'Passwords do not match',
    specialOffer: 'Special offer for Poperinge',
    discountMessage: 'Awesome! You get -10% discount exclusive to Poperinge residents.',
    localOffer: 'Vriends local offer',
    localOfferText: 'Do you live in Poperinge? Enjoy -10% discount on your order.',
    dontShowAgain: 'Don\'t show again',
    
    // Login
    loginTitle: 'Login',
    createAccount: 'Create account',
    loginButton: 'Log in',
    logging: 'Logging in...',
    passwordLabel: 'Password',
    loginError: 'Login error',
    
    // Menu
    ourMenu: 'Our Menu',
    menuSubtitle: 'Discover our selection of fresh products prepared daily.',
    addToCart: 'Add',
    unavailable: 'Unavailable',
    addedToCart: 'Added to cart ✓',
    
    // Cart
    yourCart: 'Your cart',
    emptyCart: 'Your cart is empty',
    viewMenu: 'View menu',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    pickupTime: 'Pickup time',
    placeOrder: 'Place order',
    placingOrder: 'Placing order...',
    remove: 'Remove',
    cartEmpty: 'Your cart is empty',
    orderSuccess: 'Order placed successfully!',
    summary: 'Summary',
    orderNumber: 'Order',
    
    // Profile
    profile: 'My profile',
    identity: 'Identity',
    advantages: 'Advantages',
    orders: 'My orders',
    localBadge: 'Local resident',
    noDiscount: 'No active discount',
    discountActive: 'Active discount',
    noOrders: 'No orders',
    orderStatus: 'Status',
    pickupTimeLabel: 'Pickup time',
    pending: 'Pending',
    ready: 'Ready',
    completed: 'Completed',
    cancelled: 'Cancelled',
    disconnect: 'Disconnect',
    
    // Dashboard
    orders: 'Orders',
    products: 'Products',
    contactsLeads: 'Contacts & Leads',
    users: 'Users',
    new: 'New',
    treated: 'Treated',
    read: 'Read',
    markTreated: 'Mark as treated',
    markUntreated: 'Mark as untreated',
    delete: 'Delete',
    exportCSV: 'Export CSV',
    qrCodeConfig: 'QR Code Configuration',
    qrCodeDestinationUrl: 'QR Code destination URL',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Saving...',
    qrCodeUrlUpdated: 'QR Code URL updated successfully!',
    qrCodeUrlInfo: 'This URL is the destination that the QR code will redirect to. The QR code itself points to a fixed redirect page (`/qr-redirect`) that uses this URL.',
    qrScans: 'QR Code scans',
    totalScans: 'Total',
    today: 'Today',
    thisWeek: 'This week',
    thisMonth: 'This month',
    pickupTimeLabel: 'Pickup time',
    orderTotal: 'Total',
    changeStatus: 'Change status',
    available: 'Available',
    unavailable: 'Unavailable',
    toggle: 'Toggle',
    admin: 'Admin',
    client: 'Client',
    nonLocal: 'Non local',
    reduction: 'Discount',
    noContactsToExport: 'No contacts to export',
    noUsersToExport: 'No users to export',
    deleteContactConfirm: 'Delete this contact?',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    allFieldsRequired: 'All required fields must be filled',
    consentRequired: 'Consent is required',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Récupérer la langue depuis localStorage ou utiliser 'fr' par défaut
    const savedLanguage = localStorage.getItem('vriends_language');
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    // Sauvegarder la langue dans localStorage
    localStorage.setItem('vriends_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
